image: node:16

stages:
  - deploy

pages:
  variables:
    DOCSIFY_BASE_PATH: https://GROUP_NAME.gitlab.io/-/PROJECT_PATH/docs
    docsify: $docsify
  stage: deploy
  script:
    - rm -rf public/
    - cp -r docs/ public/
    - ls
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
      changes: 
        - docs/**/*
